Repository MicrosoftDocs/power-automate-docs, pull requests merged in 2022-05, with the labels that each got.

#731 Update approvals-known-issues.md
  articles/approvals-known-issues.md
Labels: do-not-merge, power-automate/svc, Change sent to author, cloud-flow/subsvc

#717 Adding note on firewall configuration
  articles/ip-address-configuration.md
Labels: do-not-merge, power-automate/svc, Change sent to author, cloud-flow/subsvc

#732 Update how-tos-restore-deleted-flow.md
  articles/how-tos-restore-deleted-flow.md
Labels: do-not-merge, power-automate/svc, Change sent to author, cloud-flow/subsvc

#734 Update ip-address-configuration.md
  articles/ip-address-configuration.md
Labels: do-not-merge, power-automate/svc, Change sent to author, cloud-flow/subsvc

#738 Update troubleshoot.md
  articles/desktop-flows/troubleshoot.md
Labels: do-not-merge, power-automate/svc, Change sent to author, desktop-flow/subsvc

#735 Edit Request #13077 (needs Acrolinx)
  articles/forms/get-started.md
  articles/forms/how-to.md
  articles/forms/overview.md
  articles/forms/popular-scenarios.md
  articles/forms/troubleshoot-issues.md
  articles/media/forms/approval-flow-step-no.png
  articles/media/forms/approval-flow-step-yes.png
  articles/media/forms/approval-flow-step2.png
  articles/media/forms/approval-flow-step3.png
  articles/media/forms/approval-flow-step4.png
  articles/media/forms/attachment-flow-file-path.png
  articles/media/forms/attachment-flow-form-upload.png
  articles/media/forms/attachment-flow-json-schema.png
  articles/media/forms/attachment-flow-run-history.png
  articles/media/forms/attachment-flow-run-outputs.png
  articles/media/forms/attachment-flow-sample-payload.png
  articles/media/forms/attachment-flow-share-link-delete-name.png
  articles/media/forms/attachment-flow-share-link-path.png
  articles/media/forms/attachment-flow-share-link-step-final.png
  articles/media/forms/attachment-flow-share-link-step-final2.png
  articles/media/forms/attachment-flow-share-link-step.png
  articles/media/forms/attachment-flow-share-link.png
  articles/media/forms/attachment-flow-step1.png
  articles/media/forms/attachment-flow-step2.png
  articles/media/forms/email-flow-step1.png
  articles/media/forms/email-flow-step2.png
  articles/media/forms/email-flow-step3.png
  articles/media/forms/excel-flow-step1.png
  articles/media/forms/excel-flow-step2.png
  articles/media/forms/excel-flow-step3.png
  articles/media/forms/excel-flow-step4.png
  articles/media/forms/excel-flow-table-after.png
  articles/media/forms/excel-flow-table.png
  articles/media/forms/forms-action.png
  articles/media/forms/forms-trigger.png
  articles/media/forms/responder-email-flow.png
  articles/media/forms/templates-screen.png
Labels: do-not-merge, power-automate/svc, Change sent to author, docs-editor-pilot
